services:
  config-app:
    build: .
    env_file:
      - .env

    secrets:
      - db_password
      - jwt_secret

secrets:
  db_password:
    file: ./secrets/db_password.txt

  jwt_secret:
    file: ./secrets/jwt_secret.txt