# -------------------------------
# STEP 1: Base Image
# -------------------------------
# We start FROM an existing image.
# "alpine" is a very small Linux distribution (~5MB),
# commonly used for lightweight containers.
FROM alpine:latest


# -------------------------------
# STEP 2: Container Command
# -------------------------------
# CMD defines what command runs
# when the container starts.
#
# Here:
# - "echo" is a Linux command
# - "Hello from Docker!" is the output
#
# This command runs INSIDE the container,
# not on your host machine.
CMD ["echo", "Hello from Docker!"]
